apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  API_KEY: YWJjZGVmMTIzNDU2Nzg=
  DB_PASSWORD: cGFzc3dvcmQxMjM=

---
apiVersion: v1
kind: Pod
metadata:
  name: app-using-secret
spec:
  containers:
  - name: myapp-container
    image: myapp:latest
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: myapp-secret
            key: API_KEY
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: myapp-secret
            key: DB_PASSWORD

