apiVersion: v1
kind: Pod
metadata:
  name: app-with-volume
spec:
  containers:
  - name: myapp-container
    image: myapp:latest
    volumeMounts:
    - name: my-volume
      mountPath: /app/data
  volumes:
  - name: my-volume
    emptyDir: {}

